services:
  backend:
    build: ./qy_backend
    container_name: backend
    restart: always
    env_file:
      - ./qy_backend/.env
    ports:
      - "8000:80"   # 后端暴露接口
    depends_on:
      - mysql
      - redis
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    container_name: mysql8
    # 针对Mac M1/M2芯片的兼容性设置
    platform: linux/amd64
    restart: always
    environment:
      # MySQL 8默认使用caching_sha2_password认证插件
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: easy_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      # 字符集设置
      MYSQL_INITDB_ARGS: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      # 端口映射，允许宿主机访问
      - "33061:3306"
      - "33060:33060"  # MySQL 8的X协议端口
    volumes:
      # 数据持久化挂载
      - ./docker-data/mysql-data:/var/lib/mysql
      # 配置文件挂载
      - ./docker-data/mysql-conf:/etc/mysql/conf.d
      # 初始化脚本目录
      - ./docker-data/mysql-init:/docker-entrypoint-initdb.d
    # 资源限制，防止过度占用Mac资源
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    # Mac上的性能优化
    command: --default-authentication-plugin=caching_sha2_password
             --max_allowed_packet=64M
             --innodb_buffer_pool_size=256M
    networks:
      - appnet

  redis:
    image: redis:6
    container_name: redis
    volumes:
      - ./docker-data/redis-data:/data
    ports:
      - "6380:6379"
    networks:
      - appnet

  celery:
    build: .
    container_name: celery
    restart: always
    env_file:
      - .env
    working_dir: /app
    command: celery -A qy_backend worker --loglevel=info
    volumes:
      - .:/app
      - ./logs/celery:/app/logs/celery
    depends_on:
      - redis
      - mysql
    networks:
      - appnet

  celery_beat:
    build: .
    container_name: celery-beat
    restart: always
    env_file:
      - .env
    working_dir: /app
    command: celery -A qy_backend beat --loglevel=info --logfile=/app/logs/celery/celery-beat.log
    volumes:
      - .:/app
      - ./logs/celery:/app/logs/celery
    depends_on:
      - redis
      - mysql
      - celery
    networks:
      - appnet


# 网络配置
networks:
  appnet:
#    driver: bridge
    external: true
